### ISSUE TITLE
[BUG] Runtime Error when train the model using gpu.

### ISSUE THREAD

**Issue by yeeeqichen** [salesforce/ICLRec#2]
Hi, @YChen1993 

Thanks for opening source the codes!

I try to train the model with the following command:  `bash scripts/run_beauty.sh`

but encounting the following error during backward:

`Traceback (most recent call last): 
  File "main.py", line 216, in <module>
    main()
  File "main.py", line 196, in main
    trainer.train(epoch)
  File "/home/yqc/ICLRec/src/trainers.py", line 83, in train
    self.iteration(epoch, self.train_dataloader, self.cluster_dataloader)
  File "/home/yqc/ICLRec/src/trainers.py", line 344, in iteration
    joint_loss.backward()
  File "/home/yqc/anaconda3/envs/py_3.7/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yqc/anaconda3/envs/py_3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: unique_by_key: failed on 2nd step: cudaErrorInvalidValue: invalid argument`

But an interesting thing is that if I add the `--no_cuda` flag in the training script that force the model to use cpu, the codes work well.

So could you please fix this bug?

**Comment by YChen1993** [comment]
Hi @yeeeqichen, Thank you for your interest! 

I just tested the code and it should work in the following GPU environment: Gpu type: V100; CUDA version: 10.2; faiss-gpu==1.7.1.post2; Pytorch==1.2.0. Would you mind checking your environment or sharing the configuration so I can reproduce the bug? (I know there might be some incompatibility between GPU A100 and the clutering toolkit faiss-gpu) Thanks!

**Comment by yeeeqichen** [comment]
@YChen1993 Thanks for your reply! 

I will try different environments and here is my environment setting: 
faiss-gpu == 1.7.1
PyTorch == 1.10.0
cudatoolkit == 11.3.1
GPU type: 3090

**Comment by yeeeqichen** [comment]
Oh, problem solved! I try the code on another environment and it works: 

gpu type: 2080 Ti
cudatoolkit == 10.1
PyTorch == 1.4.0

maybe I think this error is due to the different cuda version, but I still don't know how to solve this if I want to use it on the newer version?

**Comment by YChen1993** [comment]
Yes. I also observe the incompatible issue of faiss-gpu and cuda 11.x env.  Maybe just wait for faiss team to fix this issue or find an alternate clustering library that supports GPU acceleration.
